### ISSUE TITLE
Handshake status 400 Bad Request

### ISSUE THREAD

**Issue by KrisshRp** [helallao/perplexity-ai#8]
Hii there I'm getting the following error 

Error: Handshake status 400 Bad Request
Traceback (most recent call last):
  File "e:\*************\perplexity-ai-main\test.py", line 73, in <module>
    print(perplexity_cli.search('Tell me somthing about life', mode='copilot', focus='internet', file=(open('myfile.txt', 'rb').read(), 'txt')))
  File "e:\*************\perplexity-ai-main\perplexity.py", line 143, in search
    self.ws.send(f'{420 + self.n}' + json.dumps([
  File "C:\*************\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_app.py", line 183, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

**Comment by helallao** [comment]
Repository updated. Use the new version.
